In [1]:
print("This is a notebook")

This is a notebook

In [2]:
spark.sql("select 1").show()

+---+
|  1|
+---+
|  1|
+---+

In [3]:
spark.sql("show tables in dev.demo_db").show(truncate=False)

+--------+---------------------+-----------+
|database|tableName            |isTemporary|
+--------+---------------------+-----------+
|demo_db |disabilitydetails    |false      |
|demo_db |stg_disabilitydetails|false      |
|demo_db |v1_disabilitydetails |false      |
+--------+---------------------+-----------+

In [4]:
spark.sql("CREATE CATALOG IF NOT EXISTS citibike_dev")
spark.sql("CREATE SCHEMA IF NOT EXISTS citibike_dev.00_landing")
spark.sql("CREATE SCHEMA IF NOT EXISTS citibike_dev.01_bronze")
spark.sql("CREATE SCHEMA IF NOT EXISTS citibike_dev.02_silver")
spark.sql("CREATE SCHEMA IF NOT EXISTS citibike_dev.03_gold")

DataFrame[]

In [5]:
spark.sql("""
CREATE VOLUME IF NOT EXISTS citibike_dev.00_landing.source_citibike_data
""")

DataFrame[]

In [ ]:
#cd C:\Users\Administrator\Desktop\dab_project\data
#databricks fs cp JC-202503-citibike-tripdata.csv dbfs:/Volumes/citibike_dev/00_landing/source_citibike_data/JC-202503-citibike-tripdata.csv